### ISSUE TITLE
new requests

### ISSUE THREAD

**Issue by fl0wb0b** [wylanswets/homebridge-sure-petcare-platform#10]
hello,
can you implement the "lock out pets" function? @wylanswets at night our cat brings mice into the house :D

**Comment by wylanswets** [comment]
Hi @fl0wb0b, that sounds terrible! I have added support for this in the latest version, 0.1.3. Please see the change log in the readme (homepage of the project) after updating on how to adjust it to your liking!

**Comment by fl0wb0b** [comment]
big thanks to your fast reaction and work!!
if i set "lock_mode": 1,2,3 the app shows me that the cat flap is locked for "in to out function" (green house in the app)
i have reinstalled the plugin, nothing changes.

**Comment by wylanswets** [comment]
Hey @fl0wb0b no worries! You are correct. That is because I'm really _really_ dumb and didn't test my own code first. The variable I used to set the intended locking mode was never sent to the lock... so essentially the intended locking mode was ignored. I have fixed that and tested my own code this time so it's "20% more guaranteed to probably work"™

**Comment by fl0wb0b** [comment]
Oh my god it works very well. thank you i love it 💯 👍

**Comment by wylanswets** [comment]
You're welcome! Glad you like it!
